name: Test EOPF JupyterHub

on:
  push:
    paths:
        - 'scripts/test_jupyterhub.py'   
  schedule:
    - cron: "*/30 * * * *"  

jobs:
  test-stac-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Pushgateway env
        run: |
          echo "EOPF_URL=https://jupyterhub.user.eopf.eodc.eu" >> $GITHUB_ENV
          echo "EOPF_USER=${{ secrets.EOPF_USER }}" >> $GITHUB_ENV
          echo "EOPF_TOKEN=${{ secrets.EOPF_TOKEN }}" >> $GITHUB_ENV
          echo "PUSHGATEWAY_URL=${{ secrets.PUSHGATEWAY_ENDPOINT }}" >> $GITHUB_ENV
          echo "PUSHGATEWAY_USERNAME=${{ secrets.PUSHGATEWAY_USERNAME }}" >> $GITHUB_ENV
          echo "PUSHGATEWAY_PASSWORD=${{ secrets.PUSHGATEWAY_PASSWORD }}" >> $GITHUB_ENV

      - name: Test EOPF JupyterHub
        run: python scripts/test_jupyterhub.py

      - name: Commit Logs
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --rebase --autostash
          git commit -m "Updated EOPF JupyterHub test logs"
          git push