name: Test STAC API

on:
  push:
    paths:
        - 'scripts/test_stac_api.py'   
  schedule:
    - cron: "*/30 * * * *"  
  workflow_dispatch:

jobs:
  test-stac-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Pushgateway env
        run: |
          echo "PUSHGATEWAY_URL=${{ secrets.PUSHGATEWAY_ENDPOINT }}" >> $GITHUB_ENV
          echo "PUSHGATEWAY_USERNAME=${{ secrets.PUSHGATEWAY_USERNAME }}" >> $GITHUB_ENV
          echo "PUSHGATEWAY_PASSWORD=${{ secrets.PUSHGATEWAY_PASSWORD }}" >> $GITHUB_ENV

      - name: Run STAC API Test
        run: python scripts/test_stac_api.py

      - name: Update HTML Report
        run: python scripts/update_html_report_api.py

      - name: Commit Logs
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --rebase --autostash
          git add results/logs/test_stac_api.log docs/index.html
          git commit -m "Updated STAC API test logs and HTML report"
          git push
