name: Test OpenStack 

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:
  push:
    paths:
        - 'scripts/test_openstack.py'
        - '.github/workflows/test_openstack.yml'      

jobs:
  openstack-test:
    runs-on: ubuntu-latest

    env:
      OPENSTACK_IMAGE_ID: ${{ secrets.IMAGE_ID }}
      OPENSTACK_FLAVOR_ID: ${{ secrets.FLAVOR_ID }}
      OPENSTACK_NETWORK_ID: ${{ secrets.NETWORK_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install openstacksdk opentelemetry-sdk opentelemetry-exporter-otlp-proto-http

      - name: Set OTel env
        run: |
          echo "OTEL_ENDPOINT=https://otel.infra.eodc.eu/v1/metrics" >> $GITHUB_ENV
          echo "OTEL_API_KEY=${{ secrets.OTEL_API_KEY }}" >> $GITHUB_ENV


      - name: Create clouds.yaml from secret
        run: |
          mkdir -p ~/.config/openstack
          echo "${{ secrets.OPENSTACK_CLOUDS_YAML }}" > ~/.config/openstack/clouds.yaml

      - name: Run OpenStack VM Test
        continue-on-error: true
        run: python scripts/test_openstack.py
