name: Test Dask Gateway

on:
  push:
    paths:
      -'scripts/test_dask.py' 
  schedule:
    - cron: "0 * * * *"  
  workflow_dispatch:  

jobs:
  test-dask:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install GDAL system deps
      run: |
        sudo add-apt-repository ppa:ubuntugis-unstable/ppa -y
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev python3-gdal
    - name: Install Python deps
      run: pip install -r requirements.txt


    - name: Set Pushgateway env
      run: |
        echo "PUSHGATEWAY_URL=${{ secrets.PUSHGATEWAY_ENDPOINT }}" >> $GITHUB_ENV
        echo "PUSHGATEWAY_USERNAME=${{ secrets.PUSHGATEWAY_USERNAME }}" >> $GITHUB_ENV
        echo "PUSHGATEWAY_PASSWORD=${{ secrets.PUSHGATEWAY_PASSWORD }}" >> $GITHUB_ENV

    - name: Run Dask Gateway Test
      env:
        EODC_USERNAME: ${{ secrets.EODC_USERNAME }}  
        EODC_PASSWORD: ${{ secrets.EODC_PASSWORD }} 
      run: python scripts/test_dask.py

    - name: Commit and push log files
      if: always()
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git pull --autostash 
        git add results/logs/test_DaskGateway.log
        git commit -m "Updated Dask Gateway test logs" || echo "No changes to commit"
        git push
