name: Test openEO API

on:
  push:
    paths:
      - 'scripts/test_openEO.py'
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  test-openeo-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install openEO Client
        run: pip install openeo

      - name: Install OTel
        run: pip install opentelemetry-sdk opentelemetry-exporter-otlp-proto-http

      - name: Set OTel env
        run: |
          echo "OTEL_ENDPOINT=https://otel.infra.eodc.eu/v1/metrics" >> $GITHUB_ENV
          echo "OTEL_API_KEY=${{ secrets.OTEL_API_KEY }}" >> $GITHUB_ENV

      - name: Add repo to PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Set Refresh Token as Environment Variable
        run: echo "OPENEO_REFRESH_TOKEN=${{ secrets.OPENEO_REFRESH_TOKEN }}" >> $GITHUB_ENV

      - name: Debug Refresh Token
        run: |
          if [ -n "$OPENEO_REFRESH_TOKEN" ]; then
            echo "Refresh Token is set in environment."
            echo "Token first 10 chars: $(echo $OPENEO_REFRESH_TOKEN | head -c 10)********"
          else
            echo "No Refresh Token found in GitHub Actions!"
            exit 1
          fi

      - name: Run openEO API Test
        continue-on-error: true
        run: python scripts/test_openEO.py
