name: Test STAC API

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"  # 10 Minutes

jobs:
  test-stac-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run STAC API Test
        run: python scripts/test_stac_api.py

      - name: Update HTML Report
        run: python scripts/update_html_report.py

      - name: Commit Logs
        if: always()
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add results/logs/* docs/index.html
          git commit -m "Updated STAC API test logs and HTML report"
          git push
