name: Test Dask Gateway

on:
  push:
    paths:
      - "scripts/test_dask.py"
  workflow_dispatch:

jobs:
  test-dask:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install \
            "dask[distributed]==2025.7.0" \
            "distributed==2025.7.0" \
            "dask-gateway"

      - name: Show installed versions
        run: |
          python --version
          python - <<'EOF'
          import dask
          import distributed
          import dask_gateway

          print(f"dask={dask.__version__}")
          print(f"distributed={distributed.__version__}")
          print(f"dask_gateway={dask_gateway.__version__}")
          EOF

      - name: Set OTel environment
        run: |
          echo "OTEL_ENDPOINT=https://otel.infra.eodc.eu/v1/metrics" >> $GITHUB_ENV
          echo "OTEL_API_KEY=${{ secrets.OTEL_API_KEY }}" >> $GITHUB_ENV

      - name: Run Dask Gateway Test
        env:
          EODC_USERNAME: ${{ secrets.EODC_USERNAME }}
          EODC_PASSWORD: ${{ secrets.EODC_PASSWORD }}
        run: python scripts/test_dask.py