name: Workshop

on:
    push: #triggered when something is pushed on main brach
      branches: 
        - main

    schedule:
        - cron: "*/10 * * * *" #triggered every 10 minutes

    workflow_dispatch: #triggered manually via github actions 
 

jobs:
  python_computation:
    runs-on: ubuntu-latest # GitHub-hosted runner
    steps:
      - name: Checkout code # clone our repository into the runner
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Specify the Python version

      - name: Install dependencies
        run: |                       #Runs command-line programs using the operating system's shell
          pip install -r requirements.txt

      - name: Run Computation Script
        run: python scripts/compute.py # Executes a Python script
